/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#001711',
        'surface-dim': '#001711',
        'surface-bright': '#263e36',
        'surface-container-lowest': '#00110c',
        'surface-container-low': '#072019',
        'surface-container': '#0b241d',
        'surface-container-high': '#162e27',
        'surface-container-highest': '#213932',
        'on-surface': '#cde9dd',
        'on-surface-variant': '#c2c8bf',
        'inverse-surface': '#cde9dd',
        'inverse-on-surface': '#1d352d',
        outline: '#8c938a',
        'outline-variant': '#424941',
        'surface-tint': '#a7d1aa',
        primary: '#a7d1aa',
        'on-primary': '#13371c',
        'primary-container': '#3a5f40',
        'on-primary-container': '#aed7b0',
        'inverse-primary': '#416747',
        secondary: '#b5ce9e',
        'on-secondary': '#223613',
        'secondary-container': '#384d27',
        'on-secondary-container': '#a4bd8d',
        tertiary: '#f7b5c4',
        'on-tertiary': '#4e222f',
        'tertiary-container': '#7b4855',
        'on-tertiary-container': '#febbca',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#c3edc5',
        'primary-fixed-dim': '#a7d1aa',
        'on-primary-fixed': '#00210a',
        'on-primary-fixed-variant': '#2a4f31',
        'secondary-fixed': '#d1ebb8',
        'secondary-fixed-dim': '#b5ce9e',
        'on-secondary-fixed': '#0e2002',
        'on-secondary-fixed-variant': '#384d27',
        'tertiary-fixed': '#ffd9e0',
        'tertiary-fixed-dim': '#f7b5c4',
        'on-tertiary-fixed': '#350e1a',
        'on-tertiary-fixed-variant': '#683845',
        background: '#001711',
        'on-background': '#cde9dd',
        'surface-variant': '#213932'
      },
      fontFamily: {
        sans: ['Geist', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      spacing: {
        'base': '4px',
        'gutter': '16px',
        'margin-mobile': '16px',
        'margin-desktop': '32px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '24px',
        'container-max': '1280px'
      }
    },
  },
  plugins: [],
}
