import { createContext, useContext, useEffect, useState } from 'react';
import type { ReactNode } from 'react';
import type { Difficulty, Problem, ProblemSet, Activity } from '../types';

export type Profile = { name: string; handle: string; goal: string; bio: string; avatar: string };
export type Theme = 'light' | 'dark';
type Store = { problems: Problem[]; problemSets: ProblemSet[]; activities: Activity[]; profile: Profile; theme: Theme; toggleTheme:()=>void; addProblem:(problem:{title:string;topic:string;difficulty:Difficulty;problemSet:string})=>void; addTrack:(name:string,totalProblems:number)=>void; importAlgoZenith:()=>number; markSolved: (id:string)=>void; updateNotes:(id:string, notes:string)=>void; advanceRevision:(id:string)=>void; updateProfile:(profile:Profile)=>void; updateGoal:(goal:string)=>void };
const seed: Problem[] = [
  {id:'1',title:'Two Sum',topic:'Arrays',difficulty:'Easy',problemSet:'Blind 75',link:'#',solved:true,revisionStage:'Revision 1',dateSolved:'2026-08-13',notes:'## Pattern\nHash map complement lookup.\n\n## Complexity\nO(n) time · O(n) space'},
  {id:'2',title:'Valid Parentheses',topic:'Stacks',difficulty:'Easy',problemSet:'Blind 75',link:'#',solved:true,revisionStage:'Solved',dateSolved:'2026-08-14'},
  {id:'3',title:'Longest Substring Without Repeating Characters',topic:'Sliding Window',difficulty:'Medium',problemSet:'NeetCode 150',link:'#',solved:false,revisionStage:'Unsolved'},
  {id:'4',title:'Product of Array Except Self',topic:'Arrays',difficulty:'Medium',problemSet:'Blind 75',link:'#',solved:false,revisionStage:'Unsolved'},
  {id:'5',title:'Binary Tree Level Order Traversal',topic:'Trees',difficulty:'Medium',problemSet:'NeetCode 150',link:'#',solved:false,revisionStage:'Unsolved'},
];
const sets=[{id:'1',name:'Blind 75',totalProblems:75,lastActivity:'Today'},{id:'2',name:'NeetCode 150',totalProblems:150,lastActivity:'Yesterday'},{id:'3',name:'LeetCode 75',totalProblems:75,lastActivity:'Aug 10'}];
const defaultProfile={name:'Bedantika Mondal',handle:'@bedantika',goal:'Crack product-based interviews',bio:'Building depth, one problem at a time.',avatar:'BM'};
const algoZenithProblems=[['Case Conversion','Easy',false,'Case-Conversion-794'],['Replacement','Easy',true,'Replacement-1158'],['Encode All','Easy',false,'Encode-All-745'],['Mirror Array','Easy',false,'Mirror-Array-1142'],['Sort Array','Easy',false,'Sort-Array-798'],['Matrix','Easy',false,'Matrix-1144'],['Sorting','Easy',true,'Sorting-1153'],['Print Pattern','Easy',false,'Print-Pattern-800'],["Let's Use Getline",'Easy',false,'Lets-Use-Getline-1184'],['Growth in 2D','Easy',false,'Growth-in-2D-521'],['Cold Storage Products','Easy',false,'Cold-Storage-Products-1392'],['Check Grade','Easy',false,'Check-Grade-796'],['Strings','Easy',false,'Strings-1186'],['Count Occurence','Easy',false,'Count-Occurence-785'],['Cup Game','Medium',false,'Cup-Game-1070']] as const;
const C=createContext<Store|undefined>(undefined); const key='algo-grove-store';
export const AppProvider=({children}:{children:ReactNode})=>{const [data]=useState(()=>{try{return JSON.parse(localStorage.getItem(key)||'') }catch{return null}}); const [problems,setProblems]=useState<Problem[]>(data?.problems||seed); const [problemSets,setProblemSets]=useState<ProblemSet[]>(data?.problemSets||sets); const [profile,setProfile]=useState<Profile>(data?.profile||defaultProfile); const [theme,setTheme]=useState<Theme>(data?.theme||'light');
useEffect(()=>{localStorage.setItem(key,JSON.stringify({problems,problemSets,profile,theme}));document.documentElement.dataset.theme=theme},[problems,problemSets,profile,theme]);
const addProblem=({title,topic,difficulty,problemSet}:{title:string;topic:string;difficulty:Difficulty;problemSet:string})=>setProblems(x=>[{id:crypto.randomUUID(),title,topic,difficulty,problemSet,link:'#',solved:false,revisionStage:'Unsolved'},...x]);
const addTrack=(name:string,totalProblems:number)=>setProblemSets(x=>[...x,{id:crypto.randomUUID(),name,totalProblems,lastActivity:'Just now'}]);
const importAlgoZenith=()=>{const track='AlgoZenith Practice';const existing=new Set(problems.map(p=>p.link));const additions=algoZenithProblems.filter(([, , ,slug])=>!existing.has(`https://maang.in/problems/${slug}`));if(!problemSets.some(s=>s.name===track))setProblemSets(x=>[...x,{id:'algozenith-practice',name:track,totalProblems:algoZenithProblems.length,lastActivity:'Imported today'}]);if(additions.length)setProblems(x=>[...additions.map(([title,difficulty,solved,slug])=>({id:`az-${slug}`,title,topic:'AlgoZenith',difficulty:difficulty as Difficulty,problemSet:track,link:`https://maang.in/problems/${slug}`,solved,revisionStage:solved?'Solved' as const:'Unsolved' as const,dateSolved:solved?new Date().toISOString():undefined})),...x]);return additions.length};
const markSolved=(id:string)=>setProblems(x=>x.map(p=>p.id===id?{...p,solved:true,revisionStage:'Solved',dateSolved:new Date().toISOString()}:p));
const updateNotes=(id:string,notes:string)=>setProblems(x=>x.map(p=>p.id===id?{...p,notes}:p));
const advanceRevision=(id:string)=>setProblems(x=>x.map(p=>p.id===id?{...p,revisionStage:p.revisionStage==='Solved'?'Revision 1':p.revisionStage==='Revision 1'?'Revision 2':p.revisionStage==='Revision 2'?'Mastered':p.revisionStage}:p));
return <C.Provider value={{problems,problemSets,activities:[],profile,theme,toggleTheme:()=>setTheme(t=>t==='light'?'dark':'light'),addProblem,addTrack,importAlgoZenith,markSolved,updateNotes,advanceRevision,updateProfile:setProfile,updateGoal:(goal)=>setProfile(p=>({...p,goal}))}}>{children}</C.Provider>};
export const useAppStore=()=>{const x=useContext(C);if(!x)throw Error('AppProvider missing');return x};
